### ISSUE TITLE
pdfjs css loading icon

### ISSUE THREAD

**Issue by blizzardengle** [caboodle-tech/pdf.js-mini-viewers#12]
The loading icon which is referenced in the CSS is an issue:

```css
.loadingIcon {
    /* ... */
    background: url("../assets/loading-icon.gif") center no-repeat;
}
```

For starters the file is missing. It would be nice to replace this with JS if possible, that way there is less files for uses to have to copy into their projects.
